name: pulmopal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  gap: ^3.0.1
  convex_bottom_bar: ^3.2.0
  get: ^4.6.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  riverpod: ^2.5.0
  flutter_riverpod: ^2.4.10
  firebase_storage: ^11.6.5
  uuid: ^4.3.3
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.3
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  google_api_headers: ^2.0.3
  http: ^1.2.0
  image_picker: ^1.0.7
  rxdart: ^0.27.7
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flare_flutter: ^3.0.2
  flutter_local_notifications: ^16.3.2
  advanced_icon: ^0.1.2
  video_player: ^2.2.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
